export const IPC_CHANNELS = {
  appInfo: 'app:get-info',
  windowCommand: 'window:command',
  notesList: 'notes:list',
  noteGet: 'note:get',
  noteUpdate: 'note:update',
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  tasksGetFeed: 'tasks:get-feed',
  tasksConnect: 'tasks:connect',
  tasksOpenPendingAuth: 'tasks:open-pending-auth',
  tasksSyncNow: 'tasks:sync-now',
  tasksStart: 'tasks:start',
  tasksGetThread: 'tasks:get-thread',
  tasksSendMessage: 'tasks:send-message',
  tasksCancelRun: 'tasks:cancel-run',
  tasksClearThread: 'tasks:clear-thread',
  tasksExecutorReconnect: 'tasks:executor-reconnect',
  tasksOpenRun: 'tasks:open-run',
  tasksRuntimeCheck: 'tasks:runtime-check',
  tasksExtractNow: 'tasks:extract-now',
  tasksEvent: 'tasks:event',
} as const;
