import type { AppSettings, Note } from './types.js';

export const mockNotes: Note[] = [
  {
    id: 'n-001',
    title: 'AI prompt engineering techniques for effective feedback generation',
    body: 'Discussion notes for effective prompt templates and evaluation loops.',
    updatedAt: '2026-02-20T22:26:00.000Z',
    timeLabel: '10:26 PM',
    groupLabel: 'Fri, Feb 20',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Prompting'],
    status: 'final',
  },
  {
    id: 'n-002',
    title: 'ICP refinement for startup portfolio companies',
    body: 'Working session notes for ICP refinement, segmentation and messaging.',
    updatedAt: '2026-02-20T15:12:00.000Z',
    timeLabel: '3:12 PM',
    groupLabel: 'Fri, Feb 20',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['GTM'],
    status: 'draft',
  },
  {
    id: 'n-003',
    title: 'Teleprompter app ideation and personal computing trends',
    body: 'Captured trends and concrete feature ideas for a teleprompter product.',
    updatedAt: '2026-02-18T11:52:00.000Z',
    timeLabel: '11:52 AM',
    groupLabel: 'Wed, Feb 18',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Ideation'],
    status: 'final',
  },
  {
    id: 'n-004',
    title: 'Test meeting for Granola MCP claw',
    body: 'Integration trial notes and edge-case behavior for MCP claw workflow.',
    updatedAt: '2026-02-10T12:50:00.000Z',
    timeLabel: '12:50 PM',
    groupLabel: 'Tue, Feb 10',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['MCP'],
    status: 'draft',
  },
  {
    id: 'n-005',
    title: 'Creating digital twin personas for fintech clients',
    body: 'Persona model draft and deployment criteria across client cohorts.',
    updatedAt: '2025-10-23T18:51:00.000Z',
    timeLabel: '6:51 PM',
    groupLabel: 'Thu, Oct 23, 2025',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Persona'],
    status: 'final',
  },
  {
    id: 'n-006',
    title: 'Weekly team sync on sales, marketing, and product strategy updates',
    body: 'Cross-functional alignment log with open issues and owners.',
    updatedAt: '2025-10-23T04:33:00.000Z',
    timeLabel: '4:33 AM',
    groupLabel: 'Thu, Oct 23, 2025',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Weekly'],
    status: 'final',
  },
  {
    id: 'n-007',
    title: 'Backchannel reference checks for candidate evaluation',
    body: 'Candidate reference check summary and decisions.',
    updatedAt: '2025-10-23T02:20:00.000Z',
    timeLabel: '2:20 AM',
    groupLabel: 'Thu, Oct 23, 2025',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Hiring'],
    status: 'draft',
  },
  {
    id: 'n-008',
    title: 'Fourthwall marketing strategy for 4:12 product retargeting',
    body: 'Retargeting strategy and creative direction notes.',
    updatedAt: '2025-10-23T01:18:00.000Z',
    timeLabel: '1:18 AM',
    groupLabel: 'Thu, Oct 23, 2025',
    ownerLabel: 'Me',
    visibility: 'private',
    attendeeCount: 1,
    attendees: ['Motasim'],
    tags: ['Marketing'],
    status: 'draft',
  },
];

export const mockSettings: AppSettings = {
  autoStart: true,
  theme: 'light',
  transcriptLanguage: 'English (US)',
  showMeetingOverlay: true,
};
